-- DOMAINS
CREATE DOMAIN D_DESC AS VARCHAR(255);
CREATE DOMAIN D_ID AS INTEGER NOT NULL;
CREATE DOMAIN D_LAST_NAME AS VARCHAR(100) NOT NULL;
CREATE DOMAIN D_NAME AS VARCHAR(100) NOT NULL;
CREATE DOMAIN D_PHONE_NUMBER AS VARCHAR(9) NOT NULL;
