-- PROCEDURES

-- Procedure: ADD_CLIENT
CREATE OR ALTER PROCEDURE ADD_CLIENT (
    P_PHONE_NUMBER D_PHONE_NUMBER,
    P_LAST_NAME D_LAST_NAME,
    P_NAME D_NAME,
    P_ID D_ID
)AS
BEGIN
    INSERT INTO CLIENTS (ID, NAME, LAST_NAME, PHONE_NUMBER)
    VALUES (:P_ID, :P_NAME, :P_LAST_NAME, :P_PHONE_NUMBER);
END

-- Procedure: ADD_PRODUCT
CREATE OR ALTER PROCEDURE ADD_PRODUCT (
    P_DESC D_DESC,
    P_NAME D_NAME,
    P_ID D_ID
)AS
BEGIN
    INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION)
    VALUES (:P_ID, :P_NAME, :P_DESC);
END

-- Procedure: GET_PRODUCTS
CREATE OR ALTER PROCEDURE GET_PRODUCTS
RETURNS (
    R_DESC D_DESC,
    R_NAME D_NAME,
    R_ID D_ID
)AS
BEGIN
    FOR SELECT ID, NAME, DESCRIPTION
        FROM PRODUCTS
        INTO :R_ID, :R_NAME, :R_DESC
    DO
    BEGIN
        SUSPEND;
    END
END
