-- PROCEDURES

-- Procedure: ADD_CLIENT
BEGIN
    INSERT INTO CLIENTS (ID, NAME, LAST_NAME, PHONE_NUMBER)
    VALUES (:P_ID, :P_NAME, :P_LAST_NAME, :P_PHONE_NUMBER);
END

-- Procedure: ADD_PRODUCT
BEGIN
    INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION)
    VALUES (:P_ID, :P_NAME, :P_DESC);
END

-- Procedure: GET_PRODUCTS
BEGIN
    FOR SELECT ID, NAME, DESCRIPTION
        FROM PRODUCTS
        INTO :R_ID, :R_NAME, :R_DESC
    DO
    BEGIN
        SUSPEND;
    END
END
