-- TABLES

-- Table: CLIENTS
CREATE TABLE CLIENTS (
    ID D_ID NOT NULL,
    NAME D_NAME,
    LAST_NAME D_LAST_NAME,
    PHONE_NUMBER D_PHONE_NUMBER
);

-- Table: PRODUCTS
CREATE TABLE PRODUCTS (
    ID D_ID NOT NULL,
    NAME D_NAME,
    DESCRIPTION D_DESC
);
